// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/meromen/rm-receiver/rmq"
)

// Injectors from wire.go:

func InitializeRmqService(queueName string) (*rmq.RmqService, error) {
	rmqConfig := rmq.NewRmqConfig(queueName)
	connection, err := rmq.NewRmqConnection(rmqConfig)
	if err != nil {
		return nil, err
	}
	channel, err := rmq.NewRmqChannel(connection)
	if err != nil {
		return nil, err
	}
	queue, err := rmq.NewRmqQueue(channel, rmqConfig)
	if err != nil {
		return nil, err
	}
	v, err := rmq.NewRqmMsgChan(channel, queue)
	if err != nil {
		return nil, err
	}
	rmqService, err := rmq.NewRmqService(connection, channel, queue, v)
	if err != nil {
		return nil, err
	}
	return rmqService, nil
}
